version: "3"
services:
  odoo:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - ./:/root/sourcecode/odoo/dev/addons:ro
    depends_on:
      - pqdb

  pqdb:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-db-data:
